name: "Scan Image"
description: "Run Trivy, Grype, and Syft on a Docker image"

inputs:
  image:
    required: true
    description: "Docker image to scan"

runs:
  using: "composite"
  steps:
    - name: Trivy filesystem scan
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
      with:
        image-ref: ${{ inputs.image }}
        format: json
        output: image-trivy.json

    - name: Grype filesystem scan
      uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2
      with:
        path: ${{ inputs.image }}
        output: image-grype.json

    - name: Syft filesystem SBOM
      uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610
      with:
        image: ${{ inputs.image }}
        output: image-sbom.json