services:

  replicate:
    image: qlik-replicate:latest
    build:
      context: ./qlik-replicate
      dockerfile: Dockerfile
    container_name: replicate
    secrets:
      - replicate_admin_password
      - replicate_license
      - replicate_master_key
    environment:
      REPLICATEDATAFOLDER: /replicate/data
      REPLICATERESTPORT: 3562
      REPLICATEADMINPASSWORDFILE: /run/secrets/replicate_admin_password
      REPLICATELICENSEFILE: /run/secrets/replicate_license
      REPLICATEMASTERKEYFILE: /run/secrets/replicate_master_key
    ports:
      - "3562:3562"
    volumes:
       - replicate-data:/replicate/data
    healthcheck:
      test: ["CMD", "/opt/attunity/replicate/bin/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
    entrypoint: ["/opt/attunity/replicate/bin/entrypoint.sh"]

secrets:
  replicate_admin_password:
    file: ./secrets/replicate_admin_password.txt
  replicate_license:
    file: ./secrets/replicate_license.txt
  replicate_master_key:
    file: ./secrets/replicate_master_key.txt

volumes:
  replicate-data:

networks:
  default:
    name: replicate-network

