name: Discover and Extract Qlik Replicate

on:
  workflow_call:
    outputs:
      matrix:
        description: "Matrix of versions with extracted paths"
        value: ${{ jobs.extract.outputs.matrix }}

jobs:
  extract:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run version discovery script
        id: discover
        run: |
          chmod +x ./scripts/get-qlik-versions.sh
          URLS=$(./scripts/get-qlik-versions.sh | grep '^https')

          MATRIX_ITEMS=()

          mkdir extracted

          while read -r URL; do
            VERSION=$(echo "$URL" | sed -n 's#.*/v\([0-9]\+\.[0-9]\+\.[0-9]\+\)/.*#\1#p')

            FILE="replicate-${VERSION}.zip"
            DIR="extracted/${VERSION}"

            curl -L "$URL" -o "$FILE"
            mkdir -p "$DIR"
            unzip -q "$FILE" -d "$DIR"

            MATRIX_ITEMS+=("{\"url\":\"$URL\",\"version\":\"$VERSION\",\"path\":\"$DIR\"}")
          done <<< "$URLS"

          JSON=$(printf '%s\n' "${MATRIX_ITEMS[@]}" | jq -s -c .)
          echo "matrix=$JSON" >> $GITHUB_OUTPUT

      - name: Set matrix output
        id: set-matrix
        run: echo "matrix=${{ steps.discover.outputs.matrix }}" >> $GITHUB_OUTPUT
